### ISSUE TITLE
> > you guys mean set the jsonschema version in the manifest like this?

### ISSUE THREAD

**Issue by vetranolorenzo** [lbbrhzn/ocpp#916] opened 2023-09-25 19:49 UTC
> > you guys mean set the jsonschema version in the manifest like this?
> > ```
> > "requirements": [ 
> >      "occp>=0.14.1",
> >       "websockets>=10.2",
> >       "jsonschema==4.19.0"
> > ],
> > "version": "v0.4.40"
> > ```
> 
> thats it

I confirm it works, remember de **colon** at the end of websockets if you add the new jsonschema version after it.

_Originally posted by @mpch13 in https://github.com/lbbrhzn/ocpp/issues/912#issuecomment-1734356918_

**Comment by lbbrhzn** [comment] 2023-09-25 21:24
Duplicate of #912

**Closed by lbbrhzn** 2023-09-25 21:24 UTC
Labels: duplicate
